FROM ghcr.io/systemed/tilemaker:master

WORKDIR /var/app

COPY script-server.sh .

ADD static /var/app/static

RUN apt-get update && apt-get install -y curl

EXPOSE 8080

HEALTHCHECK --interval=5s --timeout=2s --start-period=5s --retries=5 CMD curl -f http://localhost:8080 || exit 1

ENTRYPOINT ["./script-server.sh"]