services:
  make:
    build:
      context: tilemaker
      dockerfile: dockerfile-make
    volumes:
      - ./tilemaker:/var/app/out/
      - ./tilemaker/tmp:/var/app/tmp/

  server:
    build:
      context: tilemaker
      dockerfile: dockerfile-server
    env_file:
      - .env.dev
    volumes:
      - ./tilemaker:/var/app/out/
    ports:
      - 8080:8080
    depends_on:
      make:
        condition: service_completed_successfully

  app:
    build:
      context: app
      dockerfile: dockerfile-dev
    env_file:
      - .env.dev
    volumes:
      - ./app:/var/app
    ports:
      - 5173:5173
    depends_on:
      server:
        condition: service_healthy
