services:
  make:
    container_name: opendtk-tilemaker
    build:
      context: tilemaker
      dockerfile: dockerfile-make
    volumes:
      - ./tilemaker:/var/app/out/
      - ./tilemaker/tmp:/var/app/tmp/

  server:
    container_name: opendtk-server
    build:
      context: tilemaker
      dockerfile: dockerfile-server
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - ./tilemaker:/var/app/out/
    depends_on:
      make:
        condition: service_completed_successfully

  app:
    container_name: opendtk-app
    build:
      context: app
      dockerfile: dockerfile
    env_file:
      - .env.prod
    volumes:
      - ./app/dist:/var/app/dist/

  nginx:
    container_name: opendtk-nginx
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/dist:/var/www/html
    ports:
      - 80:80
    depends_on:
      app:
        condition: service_completed_successfully
      server:
        condition: service_healthy
