services:
  prepare:
    container_name: prepare
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./geoserver.d:/app/geoserver.d
    depends_on:
      postgis:
        condition: service_started

  geoserver:
    image: docker.osgeo.org/geoserver:2.25.3
    container_name: geoserver
    ports:
      - 8080:8080
    environment:
      - SKIP_DEMO_DATA=true
    volumes:
      - ./geoserver.d/workspaces/OpenDTK:/opt/geoserver_data/workspaces/OpenDTK
    depends_on:
      prepare:
        condition: service_completed_successfully
      postgis:
        condition: service_healthy

  postgis:
    image: postgis/postgis:16-3.5-alpine
    container_name: postgis
    environment:
      POSTGRES_DB: geoserver
      POSTGRES_USER: geoserver
      POSTGRES_PASSWORD: geoserver
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geoserver"]
      interval: 5s
      retries: 5

  pgadmin4:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.lol
      PGADMIN_DEFAULT_PASSWORD: postgis
      PGADMIN_LISTEN_PORT: 8080
      PGADMIN_DISABLE_POSTFIX: true
    volumes:
      - ./pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - 8081:8080
    depends_on:
      - postgis
