services:
  tilemaker:
    build:
      context: tilemaker
      dockerfile: dockerfile-make
    env_file:
      - .env.dev
    volumes:
      - ./tilemaker:/var/app/out/
      - ./tilemaker/tmp:/var/app/tmp/

  tileserver:
    build:
      context: tilemaker
      dockerfile: dockerfile-server
    env_file:
      - .env.dev
    volumes:
      - ./tilemaker:/var/app/out/
    ports:
      - 8080:8080
    depends_on:
      tilemaker:
        condition: service_completed_successfully

  app:
    build:
      context: app
      dockerfile: dockerfile-dev
    env_file:
      - .env.dev
    volumes:
      - ./app:/var/app
    ports:
      - 5173:5173
    depends_on:
      tileserver:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      tileserver:
        condition: service_healthy
      tilemaker:
        condition: service_completed_successfully
