FROM node:22-alpine

WORKDIR /var/app

RUN apk add curl

COPY package.json package-lock.json ./

RUN npm install

COPY . .

EXPOSE 5173

HEALTHCHECK --interval=5s --timeout=2s --start-period=5s --retries=5 CMD curl -f http://localhost:5173 || exit 1

CMD ["npm", "run", "dev"]