name: build

on:
  push:
    branches:
      - main
      - other-branches # Add any other branches you want to build without pushing to DockerHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.production.DOCKER_USERNAME }}
          password: ${{ secrets.production.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfile
          push: ${{ github.ref == 'refs/heads/main' }} # Only push if on main
          tags: |
            KomelT/OpenDTK-prepare:latest
            KomelT/OpenDTK-prepare:${{ github.sha }}
